spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 180000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: shorturl-redis
      port: 6379
      timeout: 2000
 
  kafka:
    bootstrap-servers: shorturl-kafka:29092
    consumer:
      bootstrap-servers: shorturl-kafka:29092
      group-id: shorturl-click-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: shorturl-kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: BATCH
      concurrency: 3
