spring:
  profiles:
    active: local
  application:
    name: stats-service
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
stats:
  batch:
    interval-ms: 600000