spring:
  data:
    redis:
      host: shorturl-redis
      port: 6379
      timeout: 2000
    mongodb:
      uri: mongodb://shorturl-mongo:27017/shorturl

  kafka:
    bootstrap-servers: shorturl-kafka:29092
    consumer:
      bootstrap-servers: shorturl-kafka:29092
      group-id: redirect-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: shorturl-kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: BATCH
      concurrency: 1

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
